spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql
  mail:
    host: sandbox.smtp.mailtrap.io
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  health:
    mail:
      enabled: false 


logging:
  level:
    root: WARN
    com.yourpackage: INFO

