spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hrbank
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql

  jpa:
    hibernate:
      ddl-auto: none # Entity 완성 후 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true