spring:
  application:
    name: hrbank3
  profiles:
    active: local
  mvc:
    format:
      date-time: iso # 프론트 파싱을 위한 설정 -> 테스트 필요
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

file:
  upload:
    path: ${FILE_UPLOAD_PATH:./uploads/}

backup:
  dir: ${BACKUP_DIR:./backups/}
  chunk-size: 500
  schedule:
    cron: "0 0 * * * *" # 매 시 정각에 하도록 세팅

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never